#!/bin/sh

if [ -z "$1" ]; then
  echo "Usage:" `basename $0` "<URL> [# of headlines]" >&2 ; exit 1
fi

if [ "$1" = "/." ]; then
  url="slashdot"
else
  url=$1
fi

shift

root_sh=`pwd`

if [ -f "$root_sh/$url.sed" ]; then
  file="$root_sh/$url.sed"
else
  file="$root_sh/generic.sed"
fi

if [ -z $1 ]; then
  headlines=-8
else
  headlines=-$(( $1 * 2 ))
fi

case $url in
  *slashdot*)
    if [ "$url" != "http://rss.slashdot.org/Slashdot/slashdot" ]; then
      url="http://rss.slashdot.org/Slashdot/slashdot"
    fi
    if [ -z $1 ]; then
      headlines=-9
    else
      headlines=-$(( $1 * 2 + 1 ))
    fi
    ;;
  gw-news)
    url="http://www.guildwars.com/newsarchive/rss/news-current.xml"
    ;;
  gw-updates)
    url="http://www.guildwars.com/support/gameupdates/rss/updates-current.xml"
    ;;
esac

if [ -z $1 ]; then
  shift
fi

if [ -z $1 ]; then
  data=`curl --silent $url | grep -E '(<title>|<description>)' | \
    sed -f $file | sed -n '3,$p' | \
    head $headlines | fmt -w 100`
else
  data=`curl --silent $url | grep -E '(<title>|<description>)' | \
    sed -f $file | sed -n '3,$p' | \
    head $headlines | fmt -w 100`
fi

if [ -z "$data" ]; then
  echo "No data can be found at $url"
else
  echo "$data"
fi
